### ISSUE TITLE
Importing TSX files breaks JSX options

### ISSUE THREAD

**Issue by Ascor8522** [frankleng/esbuild-ts-paths#8]
When using path aliases to import TSX files, the emitted JS code uses **the wrong settings** (at least for everything JSX-related) and doesn't use the ones provided in `tsconfig.json`.

Everything works just fine without using paths.

## Minimal reproduction

```ts
// src/index.ts
import { componentToString } from "@components/component";
console.log(componentToString()); // expected "<div></div>"
```

```ts
// src/components/component.tsx
import { h } from "preact";
import { renderToString } from "preact-render-to-string";
const Component = () => <div></div>;
export const componentToString = () => renderToString(<Component />);
```

```json
// tsconfig.json
{
	"compilerOptions": {
		"target": "esnext",
		"module": "CommonJS",
		"paths": {
			"@components/*": ["src/components/*"]
		},
		"jsx": "react",
		"jsxFactory": "h",
		"jsxFragmentFactory": "Fragment"
	},
	"include": [
		"src/**/*"
	]
}
```

```js
// build script
const esbuildDecorators = require("@anatine/esbuild-decorators").esbuildDecorators;
const tsPaths = require("esbuild-ts-paths");

require("esbuild")
	.build({
		bundle: true,
		entryPoints: [{ in: "./src/index.ts", out: "index" }],
		outdir: "./out",
		platform: "node",
		target: "node16",
		tsconfig: "./tsconfig.json",
		plugins: [
			tsPaths("./tsconfig.json"),
			esbuildDecorators({ tsconfig: "./tsconfig.json", cwd: process.cwd() }),
		],
		loader: { ".ts": "ts", ".tsx": "tsx", ".json": "json" },
		format: "cjs",
		packages: "external",
	})
	.catch(() => process.exit(1));
```

Note this example is using `preact` and not `react`.

However, the emitted code calls `React.createElement` which of course isn't installed.

**Comment by frankleng** [comment]
@Ascor8522  what error are u seeing
this plugin does nothing more than mapping file paths. has no effect on `tsconfig` or final output

**Comment by Ascor8522** [comment]
@frankleng There is no "error".
**However**, this plugin **changes the behavior of ESBuild** for other settings, **for settings this plugin is not supposed to change** or have an influence on.
Those include:
- `jsx`
- `jsxFactory`
- `jsxFragmentFactory`

**Comment by frankleng** [comment]
> @frankleng There is no "error".
> **However**, this plugin **changes the behavior of ESBuild** for other settings, **for settings this plugin is not supposed to change** or have an influence on.
> Those include:
> - `jsx`
> - `jsxFactory`
> - `jsxFragmentFactory`

If u can set me up a repo to reproduce this, I'm happy to test it out.

**Comment by Ascor8522** [comment]
> If u can set me up a repo to reproduce this, I'm happy to test it out.

Sure, the repro is available [here](https://github.com/Ascor8522/repro-esbuild-ts-paths-8).

**Comment by frankleng** [comment]
@Ascor8522  btw this was actually a bug in `esbuild`
works fine now in `0.19.10`

**Comment by Ascor8522** [comment]
Glad to hear it is fixed.

Thank you for investigating and keeping me updated, and for your awesome project.
